import {test,before,after} from 'node:test';
import assert from 'node:assert/strict';
import {createApp} from '../src/app.js';
import {tracking,searchSchema} from '../src/transit.js';
import {tokenHash} from '../src/auth.js';
const token='a'.repeat(64),other='b'.repeat(64),saved=new Map();let sequence=0;
const live={id:'operator-bus-1',source:'live',from:'Horana',to:'Colombo',mode:'bus',route:'125',date:'2099-01-01',path:[],updatedAt:new Date(Date.now()-120000),etaMinutes:5,crowdPercent:60};
const store={findSession:async h=>({userId:h===tokenHash(token)?'u1':'u2'}),findUser:async id=>({_id:id}),searchTrips:async()=>[],findTrip:async id=>id===live.id?live:null,
 updateTelemetry:async(id,data)=>{if(id!==live.id||data.updatedAt<=live.updatedAt)return null;Object.assign(live,data);return live;},
 listSaved:async userId=>[...saved.values()].filter(x=>x.userId===userId),
 saveJourney:async(userId,data)=>{const old=[...saved.values()].find(x=>x.userId===userId&&x.tripId===data.tripId&&x.date===data.date);if(old)return old;const j={id:String(++sequence),userId,...data};saved.set(j.id,j);return j;},
 renameSaved:async(userId,id,label)=>{const j=saved.get(id);if(j?.userId!==userId)return null;j.label=label;return j;},deleteSaved:async(userId,id)=>saved.get(id)?.userId===userId&&saved.delete(id)};
let server,base;before(async()=>{server=createApp(store).listen(0,'127.0.0.1');await new Promise(r=>server.once('listening',r));base=`http://127.0.0.1:${server.address().port}/api`;});after(()=>new Promise(r=>server.close(r)));
async function call(path,method='GET',body,bearer=token,extra={}){const r=await fetch(base+path,{method,headers:{'Content-Type':'application/json',Authorization:`Bearer ${bearer}`,...extra},...(body?{body:JSON.stringify(body)}:{})});return {status:r.status,data:r.status===204?null:await r.json()};}
test('search validates impossible dates, same format and transport mode',()=>{for(const date of ['2026-02-30','not-a-date'])assert.equal(searchSchema.safeParse({from:'Horana',to:'Colombo',mode:'bus',date}).success,false);});
test('bus and train demo searches are explicit and unknown routes stay empty',async()=>{let r=await call('/journeys?from=Horana&to=Colombo&mode=bus&date=2099-01-01');assert.equal(r.status,200);assert.equal(r.data.journeys.length,2);assert.equal(r.data.source,'demo');r=await call('/journeys?from=Panadura&to=Colombo&mode=train&date=2099-01-01');assert.equal(r.data.journeys[0].mode,'train');r=await call('/journeys?from=Kandy&to=Colombo&mode=bus&date=2099-01-01');assert.deepEqual(r.data.journeys,[]);});
test('live search does not silently substitute demo trips',async()=>{const r=await call('/journeys?from=Horana&to=Colombo&mode=bus&date=2099-01-01&demo=false');assert.equal(r.data.source,'live');assert.deepEqual(r.data.journeys,[]);});
test('tracking reports demo source and rejects unknown ids',async()=>{let r=await call('/journeys/demo-bus-out-0/tracking');assert.equal(r.data.source,'demo');assert.ok(Number.isFinite(r.data.position.latitude));assert.equal((await call('/journeys/unknown/tracking')).status,404);});
test('stale telemetry hides arrival and crowd estimates',()=>{const result=tracking(live);assert.equal(result.stale,true);assert.equal(result.etaMinutes,null);assert.equal(result.crowdPercent,null);});
test('saved journey CRUD is private, idempotent and validates labels',async()=>{let r=await call('/saved-journeys','POST',{tripId:'demo-bus-out-0',date:'2099-01-01'});assert.equal(r.status,201);const id=r.data.journey.id;assert.equal((await call('/saved-journeys','POST',{tripId:'demo-bus-out-0',date:'2099-01-01'})).data.journey.id,id);assert.equal((await call('/saved-journeys')).data.journeys.length,1);assert.equal((await call('/saved-journeys','GET',null,other)).data.journeys.length,0);assert.equal((await call(`/saved-journeys/${id}`,'PATCH',{label:'Office commute'},other)).status,404);assert.equal((await call(`/saved-journeys/${id}`,'PATCH',{label:''})).status,400);assert.equal((await call(`/saved-journeys/${id}`,'PATCH',{label:'Office commute'})).data.journey.label,'Office commute');assert.equal((await call(`/saved-journeys/${id}`,'DELETE',null,other)).status,404);assert.equal((await call(`/saved-journeys/${id}`,'DELETE')).status,204);assert.equal((await call('/saved-journeys')).data.journeys.length,0);});
test('GPS ingestion requires a separate operator credential and rejects stale, invalid or older updates',async()=>{const previous=process.env.TRANSIT_INGEST_KEY;process.env.TRANSIT_INGEST_KEY='c'.repeat(32);try{const body={position:{latitude:6.8,longitude:79.9},updatedAt:new Date().toISOString(),etaMinutes:4,crowdPercent:50};assert.equal((await call('/telemetry/operator-bus-1','POST',body)).status,401);const headers={'x-transit-key':'c'.repeat(32)};assert.equal((await call('/telemetry/operator-bus-1','POST',{...body,position:{latitude:99,longitude:79}},token,headers)).status,400);assert.equal((await call('/telemetry/operator-bus-1','POST',body,token,headers)).status,200);assert.equal((await call('/telemetry/operator-bus-1','POST',body,token,headers)).status,409);assert.equal((await call('/telemetry/operator-bus-1','POST',{...body,updatedAt:'2020-01-01T00:00:00.000Z'},token,headers)).status,400);}finally{if(previous===undefined)delete process.env.TRANSIT_INGEST_KEY;else process.env.TRANSIT_INGEST_KEY=previous;}});
